/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivencyRouteImport } from './routes/privency'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as CompanySlugRouteImport } from './routes/$companySlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySlugUsersRouteImport } from './routes/$companySlug.users'
import { Route as CompanySlugSettingsRouteImport } from './routes/$companySlug.settings'
import { Route as CompanySlugSalesRouteImport } from './routes/$companySlug.sales'
import { Route as CompanySlugReportsRouteImport } from './routes/$companySlug.reports'
import { Route as CompanySlugQuotesRouteImport } from './routes/$companySlug.quotes'
import { Route as CompanySlugPurchasesRouteImport } from './routes/$companySlug.purchases'
import { Route as CompanySlugProjectsRouteImport } from './routes/$companySlug.projects'
import { Route as CompanySlugProductsServicesRouteImport } from './routes/$companySlug.products-services'
import { Route as CompanySlugPosRouteImport } from './routes/$companySlug.pos'
import { Route as CompanySlugInvoicesRouteImport } from './routes/$companySlug.invoices'
import { Route as CompanySlugInventoryRouteImport } from './routes/$companySlug.inventory'
import { Route as CompanySlugHrRouteImport } from './routes/$companySlug.hr'
import { Route as CompanySlugHelpdeskRouteImport } from './routes/$companySlug.helpdesk'
import { Route as CompanySlugFinanceRouteImport } from './routes/$companySlug.finance'
import { Route as CompanySlugDashboardRouteImport } from './routes/$companySlug.dashboard'
import { Route as CompanySlugCrmRouteImport } from './routes/$companySlug.crm'
import { Route as CompanySlugAccountingRouteImport } from './routes/$companySlug.accounting'
import { Route as CompanySlugSalesIndexRouteImport } from './routes/$companySlug.sales.index'
import { Route as CompanySlugPurchasesIndexRouteImport } from './routes/$companySlug.purchases.index'
import { Route as CompanySlugPosIndexRouteImport } from './routes/$companySlug.pos.index'
import { Route as CompanySlugInventoryIndexRouteImport } from './routes/$companySlug.inventory.index'
import { Route as CompanySlugHrIndexRouteImport } from './routes/$companySlug.hr.index'
import { Route as CompanySlugFinanceIndexRouteImport } from './routes/$companySlug.finance.index'
import { Route as CompanySlugCrmIndexRouteImport } from './routes/$companySlug.crm.index'
import { Route as CompanySlugAccountingIndexRouteImport } from './routes/$companySlug.accounting.index'
import { Route as CompanySlugSalesReturnsRouteImport } from './routes/$companySlug.sales.returns'
import { Route as CompanySlugSalesQuotationsRouteImport } from './routes/$companySlug.sales.quotations'
import { Route as CompanySlugSalesOrdersRouteImport } from './routes/$companySlug.sales.orders'
import { Route as CompanySlugSalesInvoicesRouteImport } from './routes/$companySlug.sales.invoices'
import { Route as CompanySlugPurchasesVendorsRouteImport } from './routes/$companySlug.purchases.vendors'
import { Route as CompanySlugPurchasesReturnsRouteImport } from './routes/$companySlug.purchases.returns'
import { Route as CompanySlugPurchasesInvoicesRouteImport } from './routes/$companySlug.purchases.invoices'
import { Route as CompanySlugPosStockRouteImport } from './routes/$companySlug.pos.stock'
import { Route as CompanySlugPosSalesReportRouteImport } from './routes/$companySlug.pos.sales-report'
import { Route as CompanySlugPosRegisterRouteImport } from './routes/$companySlug.pos.register'
import { Route as CompanySlugPosProductsRouteImport } from './routes/$companySlug.pos.products'
import { Route as CompanySlugPosHistoryRouteImport } from './routes/$companySlug.pos.history'
import { Route as CompanySlugPosCustomersRouteImport } from './routes/$companySlug.pos.customers'
import { Route as CompanySlugPosAnalyticsRouteImport } from './routes/$companySlug.pos.analytics'
import { Route as CompanySlugInventoryWarehousesRouteImport } from './routes/$companySlug.inventory.warehouses'
import { Route as CompanySlugInventoryTransfersRouteImport } from './routes/$companySlug.inventory.transfers'
import { Route as CompanySlugHrShiftsRouteImport } from './routes/$companySlug.hr.shifts'
import { Route as CompanySlugHrPayrollsRouteImport } from './routes/$companySlug.hr.payrolls'
import { Route as CompanySlugHrLeavesRouteImport } from './routes/$companySlug.hr.leaves'
import { Route as CompanySlugHrEmployeesRouteImport } from './routes/$companySlug.hr.employees'
import { Route as CompanySlugHrAttendancesRouteImport } from './routes/$companySlug.hr.attendances'
import { Route as CompanySlugFinanceVendorPaymentsRouteImport } from './routes/$companySlug.finance.vendor-payments'
import { Route as CompanySlugFinanceRevenuesRouteImport } from './routes/$companySlug.finance.revenues'
import { Route as CompanySlugFinanceExpensesRouteImport } from './routes/$companySlug.finance.expenses'
import { Route as CompanySlugFinanceCustomerPaymentsRouteImport } from './routes/$companySlug.finance.customer-payments'
import { Route as CompanySlugFinanceBankAccountsRouteImport } from './routes/$companySlug.finance.bank-accounts'
import { Route as CompanySlugCrmPipelinesRouteImport } from './routes/$companySlug.crm.pipelines'
import { Route as CompanySlugCrmLeadsRouteImport } from './routes/$companySlug.crm.leads'
import { Route as CompanySlugCrmDealsRouteImport } from './routes/$companySlug.crm.deals'
import { Route as CompanySlugAccountingTrialBalanceRouteImport } from './routes/$companySlug.accounting.trial-balance'
import { Route as CompanySlugAccountingProfitLossRouteImport } from './routes/$companySlug.accounting.profit-loss'
import { Route as CompanySlugAccountingLedgerRouteImport } from './routes/$companySlug.accounting.ledger'
import { Route as CompanySlugAccountingChartOfAccountsRouteImport } from './routes/$companySlug.accounting.chart-of-accounts'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivencyRoute = PrivencyRouteImport.update({
  id: '/privency',
  path: '/privency',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugUsersRoute = CompanySlugUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugSettingsRoute = CompanySlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugSalesRoute = CompanySlugSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugReportsRoute = CompanySlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugQuotesRoute = CompanySlugQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugPurchasesRoute = CompanySlugPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugProjectsRoute = CompanySlugProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugProductsServicesRoute =
  CompanySlugProductsServicesRouteImport.update({
    id: '/products-services',
    path: '/products-services',
    getParentRoute: () => CompanySlugRoute,
  } as any)
const CompanySlugPosRoute = CompanySlugPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugInvoicesRoute = CompanySlugInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugInventoryRoute = CompanySlugInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugHrRoute = CompanySlugHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugHelpdeskRoute = CompanySlugHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugFinanceRoute = CompanySlugFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugDashboardRoute = CompanySlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugCrmRoute = CompanySlugCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugAccountingRoute = CompanySlugAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugSalesIndexRoute = CompanySlugSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugSalesRoute,
} as any)
const CompanySlugPurchasesIndexRoute =
  CompanySlugPurchasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugPurchasesRoute,
  } as any)
const CompanySlugPosIndexRoute = CompanySlugPosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugInventoryIndexRoute =
  CompanySlugInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugInventoryRoute,
  } as any)
const CompanySlugHrIndexRoute = CompanySlugHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugHrRoute,
} as any)
const CompanySlugFinanceIndexRoute = CompanySlugFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugFinanceRoute,
} as any)
const CompanySlugCrmIndexRoute = CompanySlugCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugCrmRoute,
} as any)
const CompanySlugAccountingIndexRoute =
  CompanySlugAccountingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAccountingRoute,
  } as any)
const CompanySlugSalesReturnsRoute = CompanySlugSalesReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => CompanySlugSalesRoute,
} as any)
const CompanySlugSalesQuotationsRoute =
  CompanySlugSalesQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => CompanySlugSalesRoute,
  } as any)
const CompanySlugSalesOrdersRoute = CompanySlugSalesOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CompanySlugSalesRoute,
} as any)
const CompanySlugSalesInvoicesRoute =
  CompanySlugSalesInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => CompanySlugSalesRoute,
  } as any)
const CompanySlugPurchasesVendorsRoute =
  CompanySlugPurchasesVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => CompanySlugPurchasesRoute,
  } as any)
const CompanySlugPurchasesReturnsRoute =
  CompanySlugPurchasesReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => CompanySlugPurchasesRoute,
  } as any)
const CompanySlugPurchasesInvoicesRoute =
  CompanySlugPurchasesInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => CompanySlugPurchasesRoute,
  } as any)
const CompanySlugPosStockRoute = CompanySlugPosStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugPosSalesReportRoute =
  CompanySlugPosSalesReportRouteImport.update({
    id: '/sales-report',
    path: '/sales-report',
    getParentRoute: () => CompanySlugPosRoute,
  } as any)
const CompanySlugPosRegisterRoute = CompanySlugPosRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugPosProductsRoute = CompanySlugPosProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugPosHistoryRoute = CompanySlugPosHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugPosCustomersRoute = CompanySlugPosCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugPosAnalyticsRoute = CompanySlugPosAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CompanySlugPosRoute,
} as any)
const CompanySlugInventoryWarehousesRoute =
  CompanySlugInventoryWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => CompanySlugInventoryRoute,
  } as any)
const CompanySlugInventoryTransfersRoute =
  CompanySlugInventoryTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => CompanySlugInventoryRoute,
  } as any)
const CompanySlugHrShiftsRoute = CompanySlugHrShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => CompanySlugHrRoute,
} as any)
const CompanySlugHrPayrollsRoute = CompanySlugHrPayrollsRouteImport.update({
  id: '/payrolls',
  path: '/payrolls',
  getParentRoute: () => CompanySlugHrRoute,
} as any)
const CompanySlugHrLeavesRoute = CompanySlugHrLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => CompanySlugHrRoute,
} as any)
const CompanySlugHrEmployeesRoute = CompanySlugHrEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => CompanySlugHrRoute,
} as any)
const CompanySlugHrAttendancesRoute =
  CompanySlugHrAttendancesRouteImport.update({
    id: '/attendances',
    path: '/attendances',
    getParentRoute: () => CompanySlugHrRoute,
  } as any)
const CompanySlugFinanceVendorPaymentsRoute =
  CompanySlugFinanceVendorPaymentsRouteImport.update({
    id: '/vendor-payments',
    path: '/vendor-payments',
    getParentRoute: () => CompanySlugFinanceRoute,
  } as any)
const CompanySlugFinanceRevenuesRoute =
  CompanySlugFinanceRevenuesRouteImport.update({
    id: '/revenues',
    path: '/revenues',
    getParentRoute: () => CompanySlugFinanceRoute,
  } as any)
const CompanySlugFinanceExpensesRoute =
  CompanySlugFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => CompanySlugFinanceRoute,
  } as any)
const CompanySlugFinanceCustomerPaymentsRoute =
  CompanySlugFinanceCustomerPaymentsRouteImport.update({
    id: '/customer-payments',
    path: '/customer-payments',
    getParentRoute: () => CompanySlugFinanceRoute,
  } as any)
const CompanySlugFinanceBankAccountsRoute =
  CompanySlugFinanceBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => CompanySlugFinanceRoute,
  } as any)
const CompanySlugCrmPipelinesRoute = CompanySlugCrmPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => CompanySlugCrmRoute,
} as any)
const CompanySlugCrmLeadsRoute = CompanySlugCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CompanySlugCrmRoute,
} as any)
const CompanySlugCrmDealsRoute = CompanySlugCrmDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => CompanySlugCrmRoute,
} as any)
const CompanySlugAccountingTrialBalanceRoute =
  CompanySlugAccountingTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => CompanySlugAccountingRoute,
  } as any)
const CompanySlugAccountingProfitLossRoute =
  CompanySlugAccountingProfitLossRouteImport.update({
    id: '/profit-loss',
    path: '/profit-loss',
    getParentRoute: () => CompanySlugAccountingRoute,
  } as any)
const CompanySlugAccountingLedgerRoute =
  CompanySlugAccountingLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => CompanySlugAccountingRoute,
  } as any)
const CompanySlugAccountingChartOfAccountsRoute =
  CompanySlugAccountingChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => CompanySlugAccountingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privency': typeof PrivencyRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/$companySlug/accounting': typeof CompanySlugAccountingRouteWithChildren
  '/$companySlug/crm': typeof CompanySlugCrmRouteWithChildren
  '/$companySlug/dashboard': typeof CompanySlugDashboardRoute
  '/$companySlug/finance': typeof CompanySlugFinanceRouteWithChildren
  '/$companySlug/helpdesk': typeof CompanySlugHelpdeskRoute
  '/$companySlug/hr': typeof CompanySlugHrRouteWithChildren
  '/$companySlug/inventory': typeof CompanySlugInventoryRouteWithChildren
  '/$companySlug/invoices': typeof CompanySlugInvoicesRoute
  '/$companySlug/pos': typeof CompanySlugPosRouteWithChildren
  '/$companySlug/products-services': typeof CompanySlugProductsServicesRoute
  '/$companySlug/projects': typeof CompanySlugProjectsRoute
  '/$companySlug/purchases': typeof CompanySlugPurchasesRouteWithChildren
  '/$companySlug/quotes': typeof CompanySlugQuotesRoute
  '/$companySlug/reports': typeof CompanySlugReportsRoute
  '/$companySlug/sales': typeof CompanySlugSalesRouteWithChildren
  '/$companySlug/settings': typeof CompanySlugSettingsRoute
  '/$companySlug/users': typeof CompanySlugUsersRoute
  '/$companySlug/accounting/chart-of-accounts': typeof CompanySlugAccountingChartOfAccountsRoute
  '/$companySlug/accounting/ledger': typeof CompanySlugAccountingLedgerRoute
  '/$companySlug/accounting/profit-loss': typeof CompanySlugAccountingProfitLossRoute
  '/$companySlug/accounting/trial-balance': typeof CompanySlugAccountingTrialBalanceRoute
  '/$companySlug/crm/deals': typeof CompanySlugCrmDealsRoute
  '/$companySlug/crm/leads': typeof CompanySlugCrmLeadsRoute
  '/$companySlug/crm/pipelines': typeof CompanySlugCrmPipelinesRoute
  '/$companySlug/finance/bank-accounts': typeof CompanySlugFinanceBankAccountsRoute
  '/$companySlug/finance/customer-payments': typeof CompanySlugFinanceCustomerPaymentsRoute
  '/$companySlug/finance/expenses': typeof CompanySlugFinanceExpensesRoute
  '/$companySlug/finance/revenues': typeof CompanySlugFinanceRevenuesRoute
  '/$companySlug/finance/vendor-payments': typeof CompanySlugFinanceVendorPaymentsRoute
  '/$companySlug/hr/attendances': typeof CompanySlugHrAttendancesRoute
  '/$companySlug/hr/employees': typeof CompanySlugHrEmployeesRoute
  '/$companySlug/hr/leaves': typeof CompanySlugHrLeavesRoute
  '/$companySlug/hr/payrolls': typeof CompanySlugHrPayrollsRoute
  '/$companySlug/hr/shifts': typeof CompanySlugHrShiftsRoute
  '/$companySlug/inventory/transfers': typeof CompanySlugInventoryTransfersRoute
  '/$companySlug/inventory/warehouses': typeof CompanySlugInventoryWarehousesRoute
  '/$companySlug/pos/analytics': typeof CompanySlugPosAnalyticsRoute
  '/$companySlug/pos/customers': typeof CompanySlugPosCustomersRoute
  '/$companySlug/pos/history': typeof CompanySlugPosHistoryRoute
  '/$companySlug/pos/products': typeof CompanySlugPosProductsRoute
  '/$companySlug/pos/register': typeof CompanySlugPosRegisterRoute
  '/$companySlug/pos/sales-report': typeof CompanySlugPosSalesReportRoute
  '/$companySlug/pos/stock': typeof CompanySlugPosStockRoute
  '/$companySlug/purchases/invoices': typeof CompanySlugPurchasesInvoicesRoute
  '/$companySlug/purchases/returns': typeof CompanySlugPurchasesReturnsRoute
  '/$companySlug/purchases/vendors': typeof CompanySlugPurchasesVendorsRoute
  '/$companySlug/sales/invoices': typeof CompanySlugSalesInvoicesRoute
  '/$companySlug/sales/orders': typeof CompanySlugSalesOrdersRoute
  '/$companySlug/sales/quotations': typeof CompanySlugSalesQuotationsRoute
  '/$companySlug/sales/returns': typeof CompanySlugSalesReturnsRoute
  '/$companySlug/accounting/': typeof CompanySlugAccountingIndexRoute
  '/$companySlug/crm/': typeof CompanySlugCrmIndexRoute
  '/$companySlug/finance/': typeof CompanySlugFinanceIndexRoute
  '/$companySlug/hr/': typeof CompanySlugHrIndexRoute
  '/$companySlug/inventory/': typeof CompanySlugInventoryIndexRoute
  '/$companySlug/pos/': typeof CompanySlugPosIndexRoute
  '/$companySlug/purchases/': typeof CompanySlugPurchasesIndexRoute
  '/$companySlug/sales/': typeof CompanySlugSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privency': typeof PrivencyRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/$companySlug/dashboard': typeof CompanySlugDashboardRoute
  '/$companySlug/helpdesk': typeof CompanySlugHelpdeskRoute
  '/$companySlug/invoices': typeof CompanySlugInvoicesRoute
  '/$companySlug/products-services': typeof CompanySlugProductsServicesRoute
  '/$companySlug/projects': typeof CompanySlugProjectsRoute
  '/$companySlug/quotes': typeof CompanySlugQuotesRoute
  '/$companySlug/reports': typeof CompanySlugReportsRoute
  '/$companySlug/settings': typeof CompanySlugSettingsRoute
  '/$companySlug/users': typeof CompanySlugUsersRoute
  '/$companySlug/accounting/chart-of-accounts': typeof CompanySlugAccountingChartOfAccountsRoute
  '/$companySlug/accounting/ledger': typeof CompanySlugAccountingLedgerRoute
  '/$companySlug/accounting/profit-loss': typeof CompanySlugAccountingProfitLossRoute
  '/$companySlug/accounting/trial-balance': typeof CompanySlugAccountingTrialBalanceRoute
  '/$companySlug/crm/deals': typeof CompanySlugCrmDealsRoute
  '/$companySlug/crm/leads': typeof CompanySlugCrmLeadsRoute
  '/$companySlug/crm/pipelines': typeof CompanySlugCrmPipelinesRoute
  '/$companySlug/finance/bank-accounts': typeof CompanySlugFinanceBankAccountsRoute
  '/$companySlug/finance/customer-payments': typeof CompanySlugFinanceCustomerPaymentsRoute
  '/$companySlug/finance/expenses': typeof CompanySlugFinanceExpensesRoute
  '/$companySlug/finance/revenues': typeof CompanySlugFinanceRevenuesRoute
  '/$companySlug/finance/vendor-payments': typeof CompanySlugFinanceVendorPaymentsRoute
  '/$companySlug/hr/attendances': typeof CompanySlugHrAttendancesRoute
  '/$companySlug/hr/employees': typeof CompanySlugHrEmployeesRoute
  '/$companySlug/hr/leaves': typeof CompanySlugHrLeavesRoute
  '/$companySlug/hr/payrolls': typeof CompanySlugHrPayrollsRoute
  '/$companySlug/hr/shifts': typeof CompanySlugHrShiftsRoute
  '/$companySlug/inventory/transfers': typeof CompanySlugInventoryTransfersRoute
  '/$companySlug/inventory/warehouses': typeof CompanySlugInventoryWarehousesRoute
  '/$companySlug/pos/analytics': typeof CompanySlugPosAnalyticsRoute
  '/$companySlug/pos/customers': typeof CompanySlugPosCustomersRoute
  '/$companySlug/pos/history': typeof CompanySlugPosHistoryRoute
  '/$companySlug/pos/products': typeof CompanySlugPosProductsRoute
  '/$companySlug/pos/register': typeof CompanySlugPosRegisterRoute
  '/$companySlug/pos/sales-report': typeof CompanySlugPosSalesReportRoute
  '/$companySlug/pos/stock': typeof CompanySlugPosStockRoute
  '/$companySlug/purchases/invoices': typeof CompanySlugPurchasesInvoicesRoute
  '/$companySlug/purchases/returns': typeof CompanySlugPurchasesReturnsRoute
  '/$companySlug/purchases/vendors': typeof CompanySlugPurchasesVendorsRoute
  '/$companySlug/sales/invoices': typeof CompanySlugSalesInvoicesRoute
  '/$companySlug/sales/orders': typeof CompanySlugSalesOrdersRoute
  '/$companySlug/sales/quotations': typeof CompanySlugSalesQuotationsRoute
  '/$companySlug/sales/returns': typeof CompanySlugSalesReturnsRoute
  '/$companySlug/accounting': typeof CompanySlugAccountingIndexRoute
  '/$companySlug/crm': typeof CompanySlugCrmIndexRoute
  '/$companySlug/finance': typeof CompanySlugFinanceIndexRoute
  '/$companySlug/hr': typeof CompanySlugHrIndexRoute
  '/$companySlug/inventory': typeof CompanySlugInventoryIndexRoute
  '/$companySlug/pos': typeof CompanySlugPosIndexRoute
  '/$companySlug/purchases': typeof CompanySlugPurchasesIndexRoute
  '/$companySlug/sales': typeof CompanySlugSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privency': typeof PrivencyRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/$companySlug/accounting': typeof CompanySlugAccountingRouteWithChildren
  '/$companySlug/crm': typeof CompanySlugCrmRouteWithChildren
  '/$companySlug/dashboard': typeof CompanySlugDashboardRoute
  '/$companySlug/finance': typeof CompanySlugFinanceRouteWithChildren
  '/$companySlug/helpdesk': typeof CompanySlugHelpdeskRoute
  '/$companySlug/hr': typeof CompanySlugHrRouteWithChildren
  '/$companySlug/inventory': typeof CompanySlugInventoryRouteWithChildren
  '/$companySlug/invoices': typeof CompanySlugInvoicesRoute
  '/$companySlug/pos': typeof CompanySlugPosRouteWithChildren
  '/$companySlug/products-services': typeof CompanySlugProductsServicesRoute
  '/$companySlug/projects': typeof CompanySlugProjectsRoute
  '/$companySlug/purchases': typeof CompanySlugPurchasesRouteWithChildren
  '/$companySlug/quotes': typeof CompanySlugQuotesRoute
  '/$companySlug/reports': typeof CompanySlugReportsRoute
  '/$companySlug/sales': typeof CompanySlugSalesRouteWithChildren
  '/$companySlug/settings': typeof CompanySlugSettingsRoute
  '/$companySlug/users': typeof CompanySlugUsersRoute
  '/$companySlug/accounting/chart-of-accounts': typeof CompanySlugAccountingChartOfAccountsRoute
  '/$companySlug/accounting/ledger': typeof CompanySlugAccountingLedgerRoute
  '/$companySlug/accounting/profit-loss': typeof CompanySlugAccountingProfitLossRoute
  '/$companySlug/accounting/trial-balance': typeof CompanySlugAccountingTrialBalanceRoute
  '/$companySlug/crm/deals': typeof CompanySlugCrmDealsRoute
  '/$companySlug/crm/leads': typeof CompanySlugCrmLeadsRoute
  '/$companySlug/crm/pipelines': typeof CompanySlugCrmPipelinesRoute
  '/$companySlug/finance/bank-accounts': typeof CompanySlugFinanceBankAccountsRoute
  '/$companySlug/finance/customer-payments': typeof CompanySlugFinanceCustomerPaymentsRoute
  '/$companySlug/finance/expenses': typeof CompanySlugFinanceExpensesRoute
  '/$companySlug/finance/revenues': typeof CompanySlugFinanceRevenuesRoute
  '/$companySlug/finance/vendor-payments': typeof CompanySlugFinanceVendorPaymentsRoute
  '/$companySlug/hr/attendances': typeof CompanySlugHrAttendancesRoute
  '/$companySlug/hr/employees': typeof CompanySlugHrEmployeesRoute
  '/$companySlug/hr/leaves': typeof CompanySlugHrLeavesRoute
  '/$companySlug/hr/payrolls': typeof CompanySlugHrPayrollsRoute
  '/$companySlug/hr/shifts': typeof CompanySlugHrShiftsRoute
  '/$companySlug/inventory/transfers': typeof CompanySlugInventoryTransfersRoute
  '/$companySlug/inventory/warehouses': typeof CompanySlugInventoryWarehousesRoute
  '/$companySlug/pos/analytics': typeof CompanySlugPosAnalyticsRoute
  '/$companySlug/pos/customers': typeof CompanySlugPosCustomersRoute
  '/$companySlug/pos/history': typeof CompanySlugPosHistoryRoute
  '/$companySlug/pos/products': typeof CompanySlugPosProductsRoute
  '/$companySlug/pos/register': typeof CompanySlugPosRegisterRoute
  '/$companySlug/pos/sales-report': typeof CompanySlugPosSalesReportRoute
  '/$companySlug/pos/stock': typeof CompanySlugPosStockRoute
  '/$companySlug/purchases/invoices': typeof CompanySlugPurchasesInvoicesRoute
  '/$companySlug/purchases/returns': typeof CompanySlugPurchasesReturnsRoute
  '/$companySlug/purchases/vendors': typeof CompanySlugPurchasesVendorsRoute
  '/$companySlug/sales/invoices': typeof CompanySlugSalesInvoicesRoute
  '/$companySlug/sales/orders': typeof CompanySlugSalesOrdersRoute
  '/$companySlug/sales/quotations': typeof CompanySlugSalesQuotationsRoute
  '/$companySlug/sales/returns': typeof CompanySlugSalesReturnsRoute
  '/$companySlug/accounting/': typeof CompanySlugAccountingIndexRoute
  '/$companySlug/crm/': typeof CompanySlugCrmIndexRoute
  '/$companySlug/finance/': typeof CompanySlugFinanceIndexRoute
  '/$companySlug/hr/': typeof CompanySlugHrIndexRoute
  '/$companySlug/inventory/': typeof CompanySlugInventoryIndexRoute
  '/$companySlug/pos/': typeof CompanySlugPosIndexRoute
  '/$companySlug/purchases/': typeof CompanySlugPurchasesIndexRoute
  '/$companySlug/sales/': typeof CompanySlugSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$companySlug'
    | '/customScript.js'
    | '/login'
    | '/privacy'
    | '/privency'
    | '/register'
    | '/setup'
    | '/users'
    | '/$companySlug/accounting'
    | '/$companySlug/crm'
    | '/$companySlug/dashboard'
    | '/$companySlug/finance'
    | '/$companySlug/helpdesk'
    | '/$companySlug/hr'
    | '/$companySlug/inventory'
    | '/$companySlug/invoices'
    | '/$companySlug/pos'
    | '/$companySlug/products-services'
    | '/$companySlug/projects'
    | '/$companySlug/purchases'
    | '/$companySlug/quotes'
    | '/$companySlug/reports'
    | '/$companySlug/sales'
    | '/$companySlug/settings'
    | '/$companySlug/users'
    | '/$companySlug/accounting/chart-of-accounts'
    | '/$companySlug/accounting/ledger'
    | '/$companySlug/accounting/profit-loss'
    | '/$companySlug/accounting/trial-balance'
    | '/$companySlug/crm/deals'
    | '/$companySlug/crm/leads'
    | '/$companySlug/crm/pipelines'
    | '/$companySlug/finance/bank-accounts'
    | '/$companySlug/finance/customer-payments'
    | '/$companySlug/finance/expenses'
    | '/$companySlug/finance/revenues'
    | '/$companySlug/finance/vendor-payments'
    | '/$companySlug/hr/attendances'
    | '/$companySlug/hr/employees'
    | '/$companySlug/hr/leaves'
    | '/$companySlug/hr/payrolls'
    | '/$companySlug/hr/shifts'
    | '/$companySlug/inventory/transfers'
    | '/$companySlug/inventory/warehouses'
    | '/$companySlug/pos/analytics'
    | '/$companySlug/pos/customers'
    | '/$companySlug/pos/history'
    | '/$companySlug/pos/products'
    | '/$companySlug/pos/register'
    | '/$companySlug/pos/sales-report'
    | '/$companySlug/pos/stock'
    | '/$companySlug/purchases/invoices'
    | '/$companySlug/purchases/returns'
    | '/$companySlug/purchases/vendors'
    | '/$companySlug/sales/invoices'
    | '/$companySlug/sales/orders'
    | '/$companySlug/sales/quotations'
    | '/$companySlug/sales/returns'
    | '/$companySlug/accounting/'
    | '/$companySlug/crm/'
    | '/$companySlug/finance/'
    | '/$companySlug/hr/'
    | '/$companySlug/inventory/'
    | '/$companySlug/pos/'
    | '/$companySlug/purchases/'
    | '/$companySlug/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$companySlug'
    | '/customScript.js'
    | '/login'
    | '/privacy'
    | '/privency'
    | '/register'
    | '/setup'
    | '/users'
    | '/$companySlug/dashboard'
    | '/$companySlug/helpdesk'
    | '/$companySlug/invoices'
    | '/$companySlug/products-services'
    | '/$companySlug/projects'
    | '/$companySlug/quotes'
    | '/$companySlug/reports'
    | '/$companySlug/settings'
    | '/$companySlug/users'
    | '/$companySlug/accounting/chart-of-accounts'
    | '/$companySlug/accounting/ledger'
    | '/$companySlug/accounting/profit-loss'
    | '/$companySlug/accounting/trial-balance'
    | '/$companySlug/crm/deals'
    | '/$companySlug/crm/leads'
    | '/$companySlug/crm/pipelines'
    | '/$companySlug/finance/bank-accounts'
    | '/$companySlug/finance/customer-payments'
    | '/$companySlug/finance/expenses'
    | '/$companySlug/finance/revenues'
    | '/$companySlug/finance/vendor-payments'
    | '/$companySlug/hr/attendances'
    | '/$companySlug/hr/employees'
    | '/$companySlug/hr/leaves'
    | '/$companySlug/hr/payrolls'
    | '/$companySlug/hr/shifts'
    | '/$companySlug/inventory/transfers'
    | '/$companySlug/inventory/warehouses'
    | '/$companySlug/pos/analytics'
    | '/$companySlug/pos/customers'
    | '/$companySlug/pos/history'
    | '/$companySlug/pos/products'
    | '/$companySlug/pos/register'
    | '/$companySlug/pos/sales-report'
    | '/$companySlug/pos/stock'
    | '/$companySlug/purchases/invoices'
    | '/$companySlug/purchases/returns'
    | '/$companySlug/purchases/vendors'
    | '/$companySlug/sales/invoices'
    | '/$companySlug/sales/orders'
    | '/$companySlug/sales/quotations'
    | '/$companySlug/sales/returns'
    | '/$companySlug/accounting'
    | '/$companySlug/crm'
    | '/$companySlug/finance'
    | '/$companySlug/hr'
    | '/$companySlug/inventory'
    | '/$companySlug/pos'
    | '/$companySlug/purchases'
    | '/$companySlug/sales'
  id:
    | '__root__'
    | '/'
    | '/$companySlug'
    | '/customScript.js'
    | '/login'
    | '/privacy'
    | '/privency'
    | '/register'
    | '/setup'
    | '/users'
    | '/$companySlug/accounting'
    | '/$companySlug/crm'
    | '/$companySlug/dashboard'
    | '/$companySlug/finance'
    | '/$companySlug/helpdesk'
    | '/$companySlug/hr'
    | '/$companySlug/inventory'
    | '/$companySlug/invoices'
    | '/$companySlug/pos'
    | '/$companySlug/products-services'
    | '/$companySlug/projects'
    | '/$companySlug/purchases'
    | '/$companySlug/quotes'
    | '/$companySlug/reports'
    | '/$companySlug/sales'
    | '/$companySlug/settings'
    | '/$companySlug/users'
    | '/$companySlug/accounting/chart-of-accounts'
    | '/$companySlug/accounting/ledger'
    | '/$companySlug/accounting/profit-loss'
    | '/$companySlug/accounting/trial-balance'
    | '/$companySlug/crm/deals'
    | '/$companySlug/crm/leads'
    | '/$companySlug/crm/pipelines'
    | '/$companySlug/finance/bank-accounts'
    | '/$companySlug/finance/customer-payments'
    | '/$companySlug/finance/expenses'
    | '/$companySlug/finance/revenues'
    | '/$companySlug/finance/vendor-payments'
    | '/$companySlug/hr/attendances'
    | '/$companySlug/hr/employees'
    | '/$companySlug/hr/leaves'
    | '/$companySlug/hr/payrolls'
    | '/$companySlug/hr/shifts'
    | '/$companySlug/inventory/transfers'
    | '/$companySlug/inventory/warehouses'
    | '/$companySlug/pos/analytics'
    | '/$companySlug/pos/customers'
    | '/$companySlug/pos/history'
    | '/$companySlug/pos/products'
    | '/$companySlug/pos/register'
    | '/$companySlug/pos/sales-report'
    | '/$companySlug/pos/stock'
    | '/$companySlug/purchases/invoices'
    | '/$companySlug/purchases/returns'
    | '/$companySlug/purchases/vendors'
    | '/$companySlug/sales/invoices'
    | '/$companySlug/sales/orders'
    | '/$companySlug/sales/quotations'
    | '/$companySlug/sales/returns'
    | '/$companySlug/accounting/'
    | '/$companySlug/crm/'
    | '/$companySlug/finance/'
    | '/$companySlug/hr/'
    | '/$companySlug/inventory/'
    | '/$companySlug/pos/'
    | '/$companySlug/purchases/'
    | '/$companySlug/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanySlugRoute: typeof CompanySlugRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivencyRoute: typeof PrivencyRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privency': {
      id: '/privency'
      path: '/privency'
      fullPath: '/privency'
      preLoaderRoute: typeof PrivencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug': {
      id: '/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/users': {
      id: '/$companySlug/users'
      path: '/users'
      fullPath: '/$companySlug/users'
      preLoaderRoute: typeof CompanySlugUsersRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/settings': {
      id: '/$companySlug/settings'
      path: '/settings'
      fullPath: '/$companySlug/settings'
      preLoaderRoute: typeof CompanySlugSettingsRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/sales': {
      id: '/$companySlug/sales'
      path: '/sales'
      fullPath: '/$companySlug/sales'
      preLoaderRoute: typeof CompanySlugSalesRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/reports': {
      id: '/$companySlug/reports'
      path: '/reports'
      fullPath: '/$companySlug/reports'
      preLoaderRoute: typeof CompanySlugReportsRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/quotes': {
      id: '/$companySlug/quotes'
      path: '/quotes'
      fullPath: '/$companySlug/quotes'
      preLoaderRoute: typeof CompanySlugQuotesRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/purchases': {
      id: '/$companySlug/purchases'
      path: '/purchases'
      fullPath: '/$companySlug/purchases'
      preLoaderRoute: typeof CompanySlugPurchasesRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/projects': {
      id: '/$companySlug/projects'
      path: '/projects'
      fullPath: '/$companySlug/projects'
      preLoaderRoute: typeof CompanySlugProjectsRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/products-services': {
      id: '/$companySlug/products-services'
      path: '/products-services'
      fullPath: '/$companySlug/products-services'
      preLoaderRoute: typeof CompanySlugProductsServicesRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/pos': {
      id: '/$companySlug/pos'
      path: '/pos'
      fullPath: '/$companySlug/pos'
      preLoaderRoute: typeof CompanySlugPosRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/invoices': {
      id: '/$companySlug/invoices'
      path: '/invoices'
      fullPath: '/$companySlug/invoices'
      preLoaderRoute: typeof CompanySlugInvoicesRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/inventory': {
      id: '/$companySlug/inventory'
      path: '/inventory'
      fullPath: '/$companySlug/inventory'
      preLoaderRoute: typeof CompanySlugInventoryRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/hr': {
      id: '/$companySlug/hr'
      path: '/hr'
      fullPath: '/$companySlug/hr'
      preLoaderRoute: typeof CompanySlugHrRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/helpdesk': {
      id: '/$companySlug/helpdesk'
      path: '/helpdesk'
      fullPath: '/$companySlug/helpdesk'
      preLoaderRoute: typeof CompanySlugHelpdeskRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/finance': {
      id: '/$companySlug/finance'
      path: '/finance'
      fullPath: '/$companySlug/finance'
      preLoaderRoute: typeof CompanySlugFinanceRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/dashboard': {
      id: '/$companySlug/dashboard'
      path: '/dashboard'
      fullPath: '/$companySlug/dashboard'
      preLoaderRoute: typeof CompanySlugDashboardRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/crm': {
      id: '/$companySlug/crm'
      path: '/crm'
      fullPath: '/$companySlug/crm'
      preLoaderRoute: typeof CompanySlugCrmRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/accounting': {
      id: '/$companySlug/accounting'
      path: '/accounting'
      fullPath: '/$companySlug/accounting'
      preLoaderRoute: typeof CompanySlugAccountingRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/sales/': {
      id: '/$companySlug/sales/'
      path: '/'
      fullPath: '/$companySlug/sales/'
      preLoaderRoute: typeof CompanySlugSalesIndexRouteImport
      parentRoute: typeof CompanySlugSalesRoute
    }
    '/$companySlug/purchases/': {
      id: '/$companySlug/purchases/'
      path: '/'
      fullPath: '/$companySlug/purchases/'
      preLoaderRoute: typeof CompanySlugPurchasesIndexRouteImport
      parentRoute: typeof CompanySlugPurchasesRoute
    }
    '/$companySlug/pos/': {
      id: '/$companySlug/pos/'
      path: '/'
      fullPath: '/$companySlug/pos/'
      preLoaderRoute: typeof CompanySlugPosIndexRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/inventory/': {
      id: '/$companySlug/inventory/'
      path: '/'
      fullPath: '/$companySlug/inventory/'
      preLoaderRoute: typeof CompanySlugInventoryIndexRouteImport
      parentRoute: typeof CompanySlugInventoryRoute
    }
    '/$companySlug/hr/': {
      id: '/$companySlug/hr/'
      path: '/'
      fullPath: '/$companySlug/hr/'
      preLoaderRoute: typeof CompanySlugHrIndexRouteImport
      parentRoute: typeof CompanySlugHrRoute
    }
    '/$companySlug/finance/': {
      id: '/$companySlug/finance/'
      path: '/'
      fullPath: '/$companySlug/finance/'
      preLoaderRoute: typeof CompanySlugFinanceIndexRouteImport
      parentRoute: typeof CompanySlugFinanceRoute
    }
    '/$companySlug/crm/': {
      id: '/$companySlug/crm/'
      path: '/'
      fullPath: '/$companySlug/crm/'
      preLoaderRoute: typeof CompanySlugCrmIndexRouteImport
      parentRoute: typeof CompanySlugCrmRoute
    }
    '/$companySlug/accounting/': {
      id: '/$companySlug/accounting/'
      path: '/'
      fullPath: '/$companySlug/accounting/'
      preLoaderRoute: typeof CompanySlugAccountingIndexRouteImport
      parentRoute: typeof CompanySlugAccountingRoute
    }
    '/$companySlug/sales/returns': {
      id: '/$companySlug/sales/returns'
      path: '/returns'
      fullPath: '/$companySlug/sales/returns'
      preLoaderRoute: typeof CompanySlugSalesReturnsRouteImport
      parentRoute: typeof CompanySlugSalesRoute
    }
    '/$companySlug/sales/quotations': {
      id: '/$companySlug/sales/quotations'
      path: '/quotations'
      fullPath: '/$companySlug/sales/quotations'
      preLoaderRoute: typeof CompanySlugSalesQuotationsRouteImport
      parentRoute: typeof CompanySlugSalesRoute
    }
    '/$companySlug/sales/orders': {
      id: '/$companySlug/sales/orders'
      path: '/orders'
      fullPath: '/$companySlug/sales/orders'
      preLoaderRoute: typeof CompanySlugSalesOrdersRouteImport
      parentRoute: typeof CompanySlugSalesRoute
    }
    '/$companySlug/sales/invoices': {
      id: '/$companySlug/sales/invoices'
      path: '/invoices'
      fullPath: '/$companySlug/sales/invoices'
      preLoaderRoute: typeof CompanySlugSalesInvoicesRouteImport
      parentRoute: typeof CompanySlugSalesRoute
    }
    '/$companySlug/purchases/vendors': {
      id: '/$companySlug/purchases/vendors'
      path: '/vendors'
      fullPath: '/$companySlug/purchases/vendors'
      preLoaderRoute: typeof CompanySlugPurchasesVendorsRouteImport
      parentRoute: typeof CompanySlugPurchasesRoute
    }
    '/$companySlug/purchases/returns': {
      id: '/$companySlug/purchases/returns'
      path: '/returns'
      fullPath: '/$companySlug/purchases/returns'
      preLoaderRoute: typeof CompanySlugPurchasesReturnsRouteImport
      parentRoute: typeof CompanySlugPurchasesRoute
    }
    '/$companySlug/purchases/invoices': {
      id: '/$companySlug/purchases/invoices'
      path: '/invoices'
      fullPath: '/$companySlug/purchases/invoices'
      preLoaderRoute: typeof CompanySlugPurchasesInvoicesRouteImport
      parentRoute: typeof CompanySlugPurchasesRoute
    }
    '/$companySlug/pos/stock': {
      id: '/$companySlug/pos/stock'
      path: '/stock'
      fullPath: '/$companySlug/pos/stock'
      preLoaderRoute: typeof CompanySlugPosStockRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/pos/sales-report': {
      id: '/$companySlug/pos/sales-report'
      path: '/sales-report'
      fullPath: '/$companySlug/pos/sales-report'
      preLoaderRoute: typeof CompanySlugPosSalesReportRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/pos/register': {
      id: '/$companySlug/pos/register'
      path: '/register'
      fullPath: '/$companySlug/pos/register'
      preLoaderRoute: typeof CompanySlugPosRegisterRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/pos/products': {
      id: '/$companySlug/pos/products'
      path: '/products'
      fullPath: '/$companySlug/pos/products'
      preLoaderRoute: typeof CompanySlugPosProductsRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/pos/history': {
      id: '/$companySlug/pos/history'
      path: '/history'
      fullPath: '/$companySlug/pos/history'
      preLoaderRoute: typeof CompanySlugPosHistoryRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/pos/customers': {
      id: '/$companySlug/pos/customers'
      path: '/customers'
      fullPath: '/$companySlug/pos/customers'
      preLoaderRoute: typeof CompanySlugPosCustomersRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/pos/analytics': {
      id: '/$companySlug/pos/analytics'
      path: '/analytics'
      fullPath: '/$companySlug/pos/analytics'
      preLoaderRoute: typeof CompanySlugPosAnalyticsRouteImport
      parentRoute: typeof CompanySlugPosRoute
    }
    '/$companySlug/inventory/warehouses': {
      id: '/$companySlug/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/$companySlug/inventory/warehouses'
      preLoaderRoute: typeof CompanySlugInventoryWarehousesRouteImport
      parentRoute: typeof CompanySlugInventoryRoute
    }
    '/$companySlug/inventory/transfers': {
      id: '/$companySlug/inventory/transfers'
      path: '/transfers'
      fullPath: '/$companySlug/inventory/transfers'
      preLoaderRoute: typeof CompanySlugInventoryTransfersRouteImport
      parentRoute: typeof CompanySlugInventoryRoute
    }
    '/$companySlug/hr/shifts': {
      id: '/$companySlug/hr/shifts'
      path: '/shifts'
      fullPath: '/$companySlug/hr/shifts'
      preLoaderRoute: typeof CompanySlugHrShiftsRouteImport
      parentRoute: typeof CompanySlugHrRoute
    }
    '/$companySlug/hr/payrolls': {
      id: '/$companySlug/hr/payrolls'
      path: '/payrolls'
      fullPath: '/$companySlug/hr/payrolls'
      preLoaderRoute: typeof CompanySlugHrPayrollsRouteImport
      parentRoute: typeof CompanySlugHrRoute
    }
    '/$companySlug/hr/leaves': {
      id: '/$companySlug/hr/leaves'
      path: '/leaves'
      fullPath: '/$companySlug/hr/leaves'
      preLoaderRoute: typeof CompanySlugHrLeavesRouteImport
      parentRoute: typeof CompanySlugHrRoute
    }
    '/$companySlug/hr/employees': {
      id: '/$companySlug/hr/employees'
      path: '/employees'
      fullPath: '/$companySlug/hr/employees'
      preLoaderRoute: typeof CompanySlugHrEmployeesRouteImport
      parentRoute: typeof CompanySlugHrRoute
    }
    '/$companySlug/hr/attendances': {
      id: '/$companySlug/hr/attendances'
      path: '/attendances'
      fullPath: '/$companySlug/hr/attendances'
      preLoaderRoute: typeof CompanySlugHrAttendancesRouteImport
      parentRoute: typeof CompanySlugHrRoute
    }
    '/$companySlug/finance/vendor-payments': {
      id: '/$companySlug/finance/vendor-payments'
      path: '/vendor-payments'
      fullPath: '/$companySlug/finance/vendor-payments'
      preLoaderRoute: typeof CompanySlugFinanceVendorPaymentsRouteImport
      parentRoute: typeof CompanySlugFinanceRoute
    }
    '/$companySlug/finance/revenues': {
      id: '/$companySlug/finance/revenues'
      path: '/revenues'
      fullPath: '/$companySlug/finance/revenues'
      preLoaderRoute: typeof CompanySlugFinanceRevenuesRouteImport
      parentRoute: typeof CompanySlugFinanceRoute
    }
    '/$companySlug/finance/expenses': {
      id: '/$companySlug/finance/expenses'
      path: '/expenses'
      fullPath: '/$companySlug/finance/expenses'
      preLoaderRoute: typeof CompanySlugFinanceExpensesRouteImport
      parentRoute: typeof CompanySlugFinanceRoute
    }
    '/$companySlug/finance/customer-payments': {
      id: '/$companySlug/finance/customer-payments'
      path: '/customer-payments'
      fullPath: '/$companySlug/finance/customer-payments'
      preLoaderRoute: typeof CompanySlugFinanceCustomerPaymentsRouteImport
      parentRoute: typeof CompanySlugFinanceRoute
    }
    '/$companySlug/finance/bank-accounts': {
      id: '/$companySlug/finance/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/$companySlug/finance/bank-accounts'
      preLoaderRoute: typeof CompanySlugFinanceBankAccountsRouteImport
      parentRoute: typeof CompanySlugFinanceRoute
    }
    '/$companySlug/crm/pipelines': {
      id: '/$companySlug/crm/pipelines'
      path: '/pipelines'
      fullPath: '/$companySlug/crm/pipelines'
      preLoaderRoute: typeof CompanySlugCrmPipelinesRouteImport
      parentRoute: typeof CompanySlugCrmRoute
    }
    '/$companySlug/crm/leads': {
      id: '/$companySlug/crm/leads'
      path: '/leads'
      fullPath: '/$companySlug/crm/leads'
      preLoaderRoute: typeof CompanySlugCrmLeadsRouteImport
      parentRoute: typeof CompanySlugCrmRoute
    }
    '/$companySlug/crm/deals': {
      id: '/$companySlug/crm/deals'
      path: '/deals'
      fullPath: '/$companySlug/crm/deals'
      preLoaderRoute: typeof CompanySlugCrmDealsRouteImport
      parentRoute: typeof CompanySlugCrmRoute
    }
    '/$companySlug/accounting/trial-balance': {
      id: '/$companySlug/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/$companySlug/accounting/trial-balance'
      preLoaderRoute: typeof CompanySlugAccountingTrialBalanceRouteImport
      parentRoute: typeof CompanySlugAccountingRoute
    }
    '/$companySlug/accounting/profit-loss': {
      id: '/$companySlug/accounting/profit-loss'
      path: '/profit-loss'
      fullPath: '/$companySlug/accounting/profit-loss'
      preLoaderRoute: typeof CompanySlugAccountingProfitLossRouteImport
      parentRoute: typeof CompanySlugAccountingRoute
    }
    '/$companySlug/accounting/ledger': {
      id: '/$companySlug/accounting/ledger'
      path: '/ledger'
      fullPath: '/$companySlug/accounting/ledger'
      preLoaderRoute: typeof CompanySlugAccountingLedgerRouteImport
      parentRoute: typeof CompanySlugAccountingRoute
    }
    '/$companySlug/accounting/chart-of-accounts': {
      id: '/$companySlug/accounting/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/$companySlug/accounting/chart-of-accounts'
      preLoaderRoute: typeof CompanySlugAccountingChartOfAccountsRouteImport
      parentRoute: typeof CompanySlugAccountingRoute
    }
  }
}

interface CompanySlugAccountingRouteChildren {
  CompanySlugAccountingChartOfAccountsRoute: typeof CompanySlugAccountingChartOfAccountsRoute
  CompanySlugAccountingLedgerRoute: typeof CompanySlugAccountingLedgerRoute
  CompanySlugAccountingProfitLossRoute: typeof CompanySlugAccountingProfitLossRoute
  CompanySlugAccountingTrialBalanceRoute: typeof CompanySlugAccountingTrialBalanceRoute
  CompanySlugAccountingIndexRoute: typeof CompanySlugAccountingIndexRoute
}

const CompanySlugAccountingRouteChildren: CompanySlugAccountingRouteChildren = {
  CompanySlugAccountingChartOfAccountsRoute:
    CompanySlugAccountingChartOfAccountsRoute,
  CompanySlugAccountingLedgerRoute: CompanySlugAccountingLedgerRoute,
  CompanySlugAccountingProfitLossRoute: CompanySlugAccountingProfitLossRoute,
  CompanySlugAccountingTrialBalanceRoute:
    CompanySlugAccountingTrialBalanceRoute,
  CompanySlugAccountingIndexRoute: CompanySlugAccountingIndexRoute,
}

const CompanySlugAccountingRouteWithChildren =
  CompanySlugAccountingRoute._addFileChildren(
    CompanySlugAccountingRouteChildren,
  )

interface CompanySlugCrmRouteChildren {
  CompanySlugCrmDealsRoute: typeof CompanySlugCrmDealsRoute
  CompanySlugCrmLeadsRoute: typeof CompanySlugCrmLeadsRoute
  CompanySlugCrmPipelinesRoute: typeof CompanySlugCrmPipelinesRoute
  CompanySlugCrmIndexRoute: typeof CompanySlugCrmIndexRoute
}

const CompanySlugCrmRouteChildren: CompanySlugCrmRouteChildren = {
  CompanySlugCrmDealsRoute: CompanySlugCrmDealsRoute,
  CompanySlugCrmLeadsRoute: CompanySlugCrmLeadsRoute,
  CompanySlugCrmPipelinesRoute: CompanySlugCrmPipelinesRoute,
  CompanySlugCrmIndexRoute: CompanySlugCrmIndexRoute,
}

const CompanySlugCrmRouteWithChildren = CompanySlugCrmRoute._addFileChildren(
  CompanySlugCrmRouteChildren,
)

interface CompanySlugFinanceRouteChildren {
  CompanySlugFinanceBankAccountsRoute: typeof CompanySlugFinanceBankAccountsRoute
  CompanySlugFinanceCustomerPaymentsRoute: typeof CompanySlugFinanceCustomerPaymentsRoute
  CompanySlugFinanceExpensesRoute: typeof CompanySlugFinanceExpensesRoute
  CompanySlugFinanceRevenuesRoute: typeof CompanySlugFinanceRevenuesRoute
  CompanySlugFinanceVendorPaymentsRoute: typeof CompanySlugFinanceVendorPaymentsRoute
  CompanySlugFinanceIndexRoute: typeof CompanySlugFinanceIndexRoute
}

const CompanySlugFinanceRouteChildren: CompanySlugFinanceRouteChildren = {
  CompanySlugFinanceBankAccountsRoute: CompanySlugFinanceBankAccountsRoute,
  CompanySlugFinanceCustomerPaymentsRoute:
    CompanySlugFinanceCustomerPaymentsRoute,
  CompanySlugFinanceExpensesRoute: CompanySlugFinanceExpensesRoute,
  CompanySlugFinanceRevenuesRoute: CompanySlugFinanceRevenuesRoute,
  CompanySlugFinanceVendorPaymentsRoute: CompanySlugFinanceVendorPaymentsRoute,
  CompanySlugFinanceIndexRoute: CompanySlugFinanceIndexRoute,
}

const CompanySlugFinanceRouteWithChildren =
  CompanySlugFinanceRoute._addFileChildren(CompanySlugFinanceRouteChildren)

interface CompanySlugHrRouteChildren {
  CompanySlugHrAttendancesRoute: typeof CompanySlugHrAttendancesRoute
  CompanySlugHrEmployeesRoute: typeof CompanySlugHrEmployeesRoute
  CompanySlugHrLeavesRoute: typeof CompanySlugHrLeavesRoute
  CompanySlugHrPayrollsRoute: typeof CompanySlugHrPayrollsRoute
  CompanySlugHrShiftsRoute: typeof CompanySlugHrShiftsRoute
  CompanySlugHrIndexRoute: typeof CompanySlugHrIndexRoute
}

const CompanySlugHrRouteChildren: CompanySlugHrRouteChildren = {
  CompanySlugHrAttendancesRoute: CompanySlugHrAttendancesRoute,
  CompanySlugHrEmployeesRoute: CompanySlugHrEmployeesRoute,
  CompanySlugHrLeavesRoute: CompanySlugHrLeavesRoute,
  CompanySlugHrPayrollsRoute: CompanySlugHrPayrollsRoute,
  CompanySlugHrShiftsRoute: CompanySlugHrShiftsRoute,
  CompanySlugHrIndexRoute: CompanySlugHrIndexRoute,
}

const CompanySlugHrRouteWithChildren = CompanySlugHrRoute._addFileChildren(
  CompanySlugHrRouteChildren,
)

interface CompanySlugInventoryRouteChildren {
  CompanySlugInventoryTransfersRoute: typeof CompanySlugInventoryTransfersRoute
  CompanySlugInventoryWarehousesRoute: typeof CompanySlugInventoryWarehousesRoute
  CompanySlugInventoryIndexRoute: typeof CompanySlugInventoryIndexRoute
}

const CompanySlugInventoryRouteChildren: CompanySlugInventoryRouteChildren = {
  CompanySlugInventoryTransfersRoute: CompanySlugInventoryTransfersRoute,
  CompanySlugInventoryWarehousesRoute: CompanySlugInventoryWarehousesRoute,
  CompanySlugInventoryIndexRoute: CompanySlugInventoryIndexRoute,
}

const CompanySlugInventoryRouteWithChildren =
  CompanySlugInventoryRoute._addFileChildren(CompanySlugInventoryRouteChildren)

interface CompanySlugPosRouteChildren {
  CompanySlugPosAnalyticsRoute: typeof CompanySlugPosAnalyticsRoute
  CompanySlugPosCustomersRoute: typeof CompanySlugPosCustomersRoute
  CompanySlugPosHistoryRoute: typeof CompanySlugPosHistoryRoute
  CompanySlugPosProductsRoute: typeof CompanySlugPosProductsRoute
  CompanySlugPosRegisterRoute: typeof CompanySlugPosRegisterRoute
  CompanySlugPosSalesReportRoute: typeof CompanySlugPosSalesReportRoute
  CompanySlugPosStockRoute: typeof CompanySlugPosStockRoute
  CompanySlugPosIndexRoute: typeof CompanySlugPosIndexRoute
}

const CompanySlugPosRouteChildren: CompanySlugPosRouteChildren = {
  CompanySlugPosAnalyticsRoute: CompanySlugPosAnalyticsRoute,
  CompanySlugPosCustomersRoute: CompanySlugPosCustomersRoute,
  CompanySlugPosHistoryRoute: CompanySlugPosHistoryRoute,
  CompanySlugPosProductsRoute: CompanySlugPosProductsRoute,
  CompanySlugPosRegisterRoute: CompanySlugPosRegisterRoute,
  CompanySlugPosSalesReportRoute: CompanySlugPosSalesReportRoute,
  CompanySlugPosStockRoute: CompanySlugPosStockRoute,
  CompanySlugPosIndexRoute: CompanySlugPosIndexRoute,
}

const CompanySlugPosRouteWithChildren = CompanySlugPosRoute._addFileChildren(
  CompanySlugPosRouteChildren,
)

interface CompanySlugPurchasesRouteChildren {
  CompanySlugPurchasesInvoicesRoute: typeof CompanySlugPurchasesInvoicesRoute
  CompanySlugPurchasesReturnsRoute: typeof CompanySlugPurchasesReturnsRoute
  CompanySlugPurchasesVendorsRoute: typeof CompanySlugPurchasesVendorsRoute
  CompanySlugPurchasesIndexRoute: typeof CompanySlugPurchasesIndexRoute
}

const CompanySlugPurchasesRouteChildren: CompanySlugPurchasesRouteChildren = {
  CompanySlugPurchasesInvoicesRoute: CompanySlugPurchasesInvoicesRoute,
  CompanySlugPurchasesReturnsRoute: CompanySlugPurchasesReturnsRoute,
  CompanySlugPurchasesVendorsRoute: CompanySlugPurchasesVendorsRoute,
  CompanySlugPurchasesIndexRoute: CompanySlugPurchasesIndexRoute,
}

const CompanySlugPurchasesRouteWithChildren =
  CompanySlugPurchasesRoute._addFileChildren(CompanySlugPurchasesRouteChildren)

interface CompanySlugSalesRouteChildren {
  CompanySlugSalesInvoicesRoute: typeof CompanySlugSalesInvoicesRoute
  CompanySlugSalesOrdersRoute: typeof CompanySlugSalesOrdersRoute
  CompanySlugSalesQuotationsRoute: typeof CompanySlugSalesQuotationsRoute
  CompanySlugSalesReturnsRoute: typeof CompanySlugSalesReturnsRoute
  CompanySlugSalesIndexRoute: typeof CompanySlugSalesIndexRoute
}

const CompanySlugSalesRouteChildren: CompanySlugSalesRouteChildren = {
  CompanySlugSalesInvoicesRoute: CompanySlugSalesInvoicesRoute,
  CompanySlugSalesOrdersRoute: CompanySlugSalesOrdersRoute,
  CompanySlugSalesQuotationsRoute: CompanySlugSalesQuotationsRoute,
  CompanySlugSalesReturnsRoute: CompanySlugSalesReturnsRoute,
  CompanySlugSalesIndexRoute: CompanySlugSalesIndexRoute,
}

const CompanySlugSalesRouteWithChildren =
  CompanySlugSalesRoute._addFileChildren(CompanySlugSalesRouteChildren)

interface CompanySlugRouteChildren {
  CompanySlugAccountingRoute: typeof CompanySlugAccountingRouteWithChildren
  CompanySlugCrmRoute: typeof CompanySlugCrmRouteWithChildren
  CompanySlugDashboardRoute: typeof CompanySlugDashboardRoute
  CompanySlugFinanceRoute: typeof CompanySlugFinanceRouteWithChildren
  CompanySlugHelpdeskRoute: typeof CompanySlugHelpdeskRoute
  CompanySlugHrRoute: typeof CompanySlugHrRouteWithChildren
  CompanySlugInventoryRoute: typeof CompanySlugInventoryRouteWithChildren
  CompanySlugInvoicesRoute: typeof CompanySlugInvoicesRoute
  CompanySlugPosRoute: typeof CompanySlugPosRouteWithChildren
  CompanySlugProductsServicesRoute: typeof CompanySlugProductsServicesRoute
  CompanySlugProjectsRoute: typeof CompanySlugProjectsRoute
  CompanySlugPurchasesRoute: typeof CompanySlugPurchasesRouteWithChildren
  CompanySlugQuotesRoute: typeof CompanySlugQuotesRoute
  CompanySlugReportsRoute: typeof CompanySlugReportsRoute
  CompanySlugSalesRoute: typeof CompanySlugSalesRouteWithChildren
  CompanySlugSettingsRoute: typeof CompanySlugSettingsRoute
  CompanySlugUsersRoute: typeof CompanySlugUsersRoute
}

const CompanySlugRouteChildren: CompanySlugRouteChildren = {
  CompanySlugAccountingRoute: CompanySlugAccountingRouteWithChildren,
  CompanySlugCrmRoute: CompanySlugCrmRouteWithChildren,
  CompanySlugDashboardRoute: CompanySlugDashboardRoute,
  CompanySlugFinanceRoute: CompanySlugFinanceRouteWithChildren,
  CompanySlugHelpdeskRoute: CompanySlugHelpdeskRoute,
  CompanySlugHrRoute: CompanySlugHrRouteWithChildren,
  CompanySlugInventoryRoute: CompanySlugInventoryRouteWithChildren,
  CompanySlugInvoicesRoute: CompanySlugInvoicesRoute,
  CompanySlugPosRoute: CompanySlugPosRouteWithChildren,
  CompanySlugProductsServicesRoute: CompanySlugProductsServicesRoute,
  CompanySlugProjectsRoute: CompanySlugProjectsRoute,
  CompanySlugPurchasesRoute: CompanySlugPurchasesRouteWithChildren,
  CompanySlugQuotesRoute: CompanySlugQuotesRoute,
  CompanySlugReportsRoute: CompanySlugReportsRoute,
  CompanySlugSalesRoute: CompanySlugSalesRouteWithChildren,
  CompanySlugSettingsRoute: CompanySlugSettingsRoute,
  CompanySlugUsersRoute: CompanySlugUsersRoute,
}

const CompanySlugRouteWithChildren = CompanySlugRoute._addFileChildren(
  CompanySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanySlugRoute: CompanySlugRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PrivencyRoute: PrivencyRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
